# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGFhNDc0MWJlYmE2YzYzYjM3YmU4NzFmNmQxMzBlZTMzZWVkY2IwYTRlN2JhZGI2ZTJiNzg2MWI5MTI3NmY0NWZkYWNmMjM4NWEwZjg3ZjJiMWQ1NTc4ZTZmZjA5MWI0ZDRjMDc1YWVmZWJmZjVlOGI4NDEzY2NhMjU2MzVhN2Q=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
